apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  labels:
    app: frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: ifilyaninitmo/itdt-contained-frontend:master
        ports:
        - containerPort: 3000
        env:
          - name: REACT_APP_USERNAME
            valueFrom: 
              configMapKeyRef:
                name: app-config
                key: username
          - name: REACT_APP_COMPANY_NAME
            valueFrom: 
              configMapKeyRef:
                name: app-config
                key: company_name
        



    